# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zhanhui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_phone', models.IntegerField(blank=True, max_length=11, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('we_chat', models.CharField(blank=True, max_length=50, null=True)),
                ('qq', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_way', models.CharField(max_length=30, verbose_name='支付方式')),
                ('pay_account', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='支付金额')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '展会表',
                'verbose_name_plural': '展会表',
            },
        ),
    ]
