# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zhanhui',
            name='note',
        ),
        migrations.AlterField(
            model_name='zhanhui',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='zhanhui',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='zhanhui',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='zhanhui',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='zhanhui',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='zhanhui',
            name='name_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='联系人电话'),
        ),
        migrations.AlterField(
            model_name='zhanhui',
            name='qq',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='qq'),
        ),
        migrations.AlterField(
            model_name='zhanhui',
            name='we_chat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='微信'),
        ),
    ]
