# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180104_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zhanhui',
            old_name='name_phone',
            new_name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='zhanhui',
            name='company',
        ),
        migrations.AddField(
            model_name='zhanhui',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='zhanhui',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='zhanhui',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='zhanhui',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='zhanhui',
            name='pay_account',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='支付金额'),
        ),
        migrations.AlterField(
            model_name='zhanhui',
            name='pay_way',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='支付方式'),
        ),
    ]
