# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_zhanhui_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhanhui',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='联系人电话'),
        ),
        migrations.AlterField(
            model_name='zhanhui',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='电话'),
        ),
    ]
