# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180104_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhanhui',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='开户银行'),
        ),
        migrations.AddField(
            model_name='zhanhui',
            name='kahao',
            field=models.IntegerField(blank=True, null=True, verbose_name='卡号后五位'),
        ),
        migrations.AddField(
            model_name='zhanhui',
            name='zhifubao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='支付宝账号'),
        ),
    ]
