# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180105_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhanhui',
            name='pay_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='支付金额'),
        ),
    ]
