# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180105_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhanhui',
            name='status',
            field=models.IntegerField(default=0, verbose_name='收款状态'),
        ),
    ]
